server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://your-git-config-repo-url

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/